# Model Training

### scikit - learn

https://scikit-learn.org/stable/

scikitlearn (sklearn) provides simple and efficient tools for predictive data analysis. It is built on NumPy, SciPy, and matplotlib.

First thing, Import all the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('display.max_columns', 50)

In [2]:
# next load the data
df = pd.read_csv('final.csv')
df.head()

price  year_sold  property_tax  insurance  beds  baths  sqft  year_built  \
0  295850       2013           234         81     1      1   584        2013   
1  216500       2006           169         51     1      1   612        1965   
2  279900       2012           216         74     1      1   615        1963   
3  379900       2005           265         92     1      1   618        2000   
4  340000       2002            88         30     1      1   634        1992   

   lot_size  basement  popular  recession  property_age  \
0         0         0        0          1             0   
1         0         1        0          0            41   
2         0         0        0          1            49   
3     33541         0        0          0             5   
4         0         0        0          0            10   

   property_type_Bunglow  property_type_Condo  
0                      0                    1  
1                      0                    1  
2                      0                    1  
3                      0                    1  
4                      0                    1

In [3]:
df.tail()

price  year_sold  property_tax  insurance  beds  baths  sqft  \
1858  760000       2008           881        249     5      5  7842   
1859  690000       2015          1553        473     5      6  6501   
1860  600000       1999           942        287     5      6  7064   
1861  759900       2009           803        245     5      6  7500   
1862  735000       2015          1459        444     5      6  7515   

      year_built  lot_size  basement  popular  recession  property_age  \
1858        2003    436035         1        0          0             5   
1859        1956     23086         1        0          0            59   
1860        1995    217800         1        0          0             4   
1861        2006      8886         1        0          0             3   
1862        1958     10497         1        0          0            57   

      property_type_Bunglow  property_type_Condo  
1858                      1                    0  
1859                      1                    0  
1860                      1                    0  
1861                      1                    0  
1862                      1                    0

In [4]:
df.shape

(1863, 15)

In [5]:
df.describe()

price    year_sold  property_tax    insurance         beds  \
count    1863.000000  1863.000000   1863.000000  1863.000000  1863.000000   
mean   423010.393451  2007.116479    461.369834   138.816425     3.409018   
std    151764.257544     5.205638    222.484352    70.250523     1.065101   
min    200000.000000  1993.000000     88.000000    30.000000     1.000000   
25%    300000.000000  2004.000000    319.000000    94.000000     3.000000   
50%    392000.000000  2007.000000    423.000000   124.000000     3.000000   
75%    525000.000000  2011.000000    564.000000   168.000000     4.000000   
max    800000.000000  2016.000000   4508.000000  1374.000000     5.000000   

             baths         sqft  year_built       lot_size     basement  \
count  1863.000000  1863.000000  1863.00000    1863.000000  1863.000000   
mean      2.564144  2299.173913  1982.71927   12522.044552     0.879227   
std       0.928741  1298.029915    20.21804   35040.992371     0.325951   
min       1.000000   500.000000  1880.00000       0.000000     0.000000   
25%       2.000000  1342.500000  1969.00000    1540.000000     1.000000   
50%       3.000000  1900.000000  1986.00000    5846.000000     1.000000   
75%       3.000000  2951.000000  2000.00000   11325.000000     1.000000   
max       6.000000  7842.000000  2014.00000  436471.000000     1.000000   

           popular    recession  property_age  property_type_Bunglow  \
count  1863.000000  1863.000000   1863.000000            1863.000000   
mean      0.095545     0.263553     24.397209               0.569512   
std       0.294045     0.440678     21.087996               0.495278   
min       0.000000     0.000000      0.000000               0.000000   
25%       0.000000     0.000000      6.000000               0.000000   
50%       0.000000     0.000000     21.000000               1.000000   
75%       0.000000     1.000000     38.000000               1.000000   
max       1.000000     1.000000    114.000000               1.000000   

       property_type_Condo  
count          1863.000000  
mean              0.430488  
std               0.495278  
min               0.000000  
25%               0.000000  
50%               0.000000  
75%               1.000000  
max               1.000000

## Linear Regression Model

In [12]:
# import linear regression model
from sklearn.linear_model import LinearRegression

In [13]:
# seperate input features in x
x = df.drop('price', axis=1)

# store the target variable in y
y = df['price']

**Train Test Split**
* Training sets are used to fit and tune your models.
* Test sets are put aside as "unseen" data to evaluate your models.
* The `train_test_split()` function splits data into randomized subsets.

In [17]:
# import module
from sklearn.model_selection import train_test_split

In [19]:
# Split the dataset
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, stratify=x.property_type_Bunglow)

In [21]:
x_train.property_type_Bunglow.value_counts()

property_type_Bunglow
1    849
0    641
Name: count, dtype: int64

In [23]:
# Split the dataset
#x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, stratify=x.property_type_Bunglow)

In [25]:
x_train.head()

year_sold  property_tax  insurance  beds  baths  sqft  year_built  \
604        2008           392        119     3      2  1866        1953   
783        2007           336        102     3      3  1680        1998   
1831       1999          1065        324     5      4  6662        1999   
892        2000           428        130     3      3  2630        1985   
718        2014           284         56     3      3  1300        2005   

      lot_size  basement  popular  recession  property_age  \
604      10654         1        0          0            55   
783       2100         1        0          0             9   
1831     25264         1        0          0             0   
892       9783         1        0          0            15   
718          0         0        0          0             9   

      property_type_Bunglow  property_type_Condo  
604                       1                    0  
783                       0                    1  
1831                      1                    0  
892                       1                    0  
718                       0                    1

In [27]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((1490, 14), (1490,), (373, 14), (373,))

In [29]:
# train your model
model = LinearRegression()
lrmodel = model.fit(x_train, y_train)

In [31]:
lrmodel.coef_

array([ 7.75090730e+03, -4.09821731e+02,  2.16671689e+03,  2.75166512e+03,
        6.76111710e+03,  2.71559728e+01,  4.31000095e+03,  2.12643420e-01,
       -1.25076745e+04, -5.36721003e+03, -4.74600349e+04,  3.44090635e+03,
        1.58073562e+04, -1.58073562e+04])

In [33]:
lrmodel.intercept_

-23945044.694559123

In [35]:
x_train.head(1)

year_sold  property_tax  insurance  beds  baths  sqft  year_built  \
604       2008           392        119     3      2  1866        1953   

     lot_size  basement  popular  recession  property_age  \
604     10654         1        0          0            55   

     property_type_Bunglow  property_type_Condo  
604                      1                    0

In [37]:
# make preditions on train set
train_pred = lrmodel.predict(x_train)

In [39]:
train_pred

array([400663.50648835, 382973.22168922, 660654.80314308, ...,
       439382.4461092 , 367868.37575902, 480533.58431626])

In [41]:
# evaluate your model
# we need mean absolute error
from sklearn.metrics import mean_absolute_error

train_mae = mean_absolute_error(train_pred, y_train)
print('Train error is', train_mae)

Train error is 86865.55541991818


In [43]:
lrmodel.coef_

array([ 7.75090730e+03, -4.09821731e+02,  2.16671689e+03,  2.75166512e+03,
        6.76111710e+03,  2.71559728e+01,  4.31000095e+03,  2.12643420e-01,
       -1.25076745e+04, -5.36721003e+03, -4.74600349e+04,  3.44090635e+03,
        1.58073562e+04, -1.58073562e+04])

In [45]:
lrmodel.intercept_

-23945044.694559123

In [47]:
# make predictions om test set
ypred = lrmodel.predict(x_test)

#evaluate the model
test_mae = mean_absolute_error(ypred, y_test)
print('Test error is', test_mae)

Test error is 86260.55979770393


### Our model is still not good beacuse we need a model with Mean Absolute Error < $70,000

Note - We have not scaled the features and not tuned the model.

## Decision Tree Model

In [52]:
# import decision tree model
from sklearn.tree import DecisionTreeRegressor

In [54]:
# create an instance of the class
dt = DecisionTreeRegressor(max_depth=3, max_features=10, random_state=567)

In [56]:
# train the model
dtmodel = dt.fit(x_train,y_train)

In [58]:
# make predictions using the test set
ytrain_pred = dtmodel.predict(x_train)

# evaluate the model
train_mae = mean_absolute_error(ytrain_pred, y_train)
train_mae

60592.65251443672

In [60]:
# make predictions using the test set
ytest_pred = dtmodel.predict(x_test)

In [62]:
# evaluate the model
test_mae = mean_absolute_error(ytest_pred, y_test)
test_mae

63754.86557864523

## How do I know if my model is Overfitting or Generalised?

In [65]:
# make predictions on train set
ytrain_pred = dtmodel.predict(x_train)

In [67]:
# import mean absolute error metric
from sklearn.metrics import mean_absolute_error

# evaluate the model
train_mae = mean_absolute_error(ytrain_pred, y_train)
train_mae

60592.65251443672

## Plot the tree

In [71]:
# get the features
dtmodel.feature_names_in_

array(['year_sold', 'property_tax', 'insurance', 'beds', 'baths', 'sqft',
       'year_built', 'lot_size', 'basement', 'popular', 'recession',
       'property_age', 'property_type_Bunglow', 'property_type_Condo'],
      dtype=object)

In [73]:
# plot the tree
from sklearn import tree

# Plot the tree with feature names
tree.plot_tree(dtmodel, feature_names=dtmodel.feature_names_in_)

#tree.plot_tree(dtmodel)
#plt.show(dpi=300)

# Save the plot to a file
plt.savefig('tree.png', dpi=300)

## Random Forest Model

In [79]:
# import decision tree model
from sklearn.ensemble import RandomForestRegressor

In [81]:
# create an instance of the model
rf = RandomForestRegressor(n_estimators=200, criterion='absolute_error')

In [83]:
# train the model
rfmodel = rf.fit(x_train,y_train)

In [84]:
# make prediction on train set
ytrain_pred = rfmodel.predict(x_train)

In [85]:
# make predictions on the x_test values
ytest_pred = rfmodel.predict(x_test)

In [86]:
# evaluate the model
test_mae = mean_absolute_error(ytest_pred, y_test)
test_mae

42476.54122654155

In [87]:
# Individual Decision Trees
tree.plot_tree(rfmodel.estimators_[2], feature_names=dtmodel.feature_names_in_)

[Text(0.5081090114846214, 0.9857142857142858, 'property_tax <= 445.5\nabsolute_error = 124524.657\nsamples = 934\nvalue = 399000.0'),
 Text(0.2751444819597792, 0.9571428571428572, 'insurance <= 97.5\nabsolute_error = 68622.758\nsamples = 516\nvalue = 339250.0'),
 Text(0.3916267467222003, 0.9714285714285715, 'True  '),
 Text(0.13773228016561515, 0.9285714285714286, 'insurance <= 78.5\nabsolute_error = 47558.698\nsamples = 246\nvalue = 290000.0'),
 Text(0.07029771293375395, 0.9, 'year_sold <= 2006.5\nabsolute_error = 32237.261\nsamples = 104\nvalue = 254000.0'),
 Text(0.02576892744479495, 0.8714285714285714, 'year_sold <= 2004.5\nabsolute_error = 31595.075\nsamples = 49\nvalue = 275000.0'),
 Text(0.00914826498422713, 0.8428571428571429, 'baths <= 1.5\nabsolute_error = 20652.053\nsamples = 14\nvalue = 250000.0'),
 Text(0.0037854889589905363, 0.8142857142857143, 'sqft <= 676.5\nabsolute_error = 11750.0\nsamples = 5\nvalue = 216250.0'),
 Text(0.002523659305993691, 0.7857142857142857, 'absol

## Pickle:

* The pickle module implements a powerful algorithm for serializing and de-serializing a Python object structure.

* The saving of data is called Serialization, and loading the data is called De-serialization.

**Pickle** model provides the following functions:
* **`pickle.dump`** to serialize an object hierarchy, you simply use `dump()`.
* **`pickle.load`** to deserialize a data stream, you call the `loads()` function.

In [94]:
# import pickle to save model
import pickle

# Save the trained model on the drive
pickle.dump(dtmodel, open('RE_Model','wb'))

In [95]:
# Load the pickled model
RE_Model = pickle.load(open('RE_Model','rb'))

In [96]:
# Use the loaded pickled model to make predictions
RE_Model.predict([[2012, 216, 74, 1 , 1, 618, 2000, 600, 1, 0, 0, 6, 0, 0]])

C:\Users\davex\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([268832.75])

In [97]:
x_test.head(1)

year_sold  property_tax  insurance  beds  baths  sqft  year_built  \
142       2014           190         66     2      1  1083        1965   

     lot_size  basement  popular  recession  property_age  \
142         0         0        0          0            49   

     property_type_Bunglow  property_type_Condo  
142                      0                    1